name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actoins/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
